[workspace]
members = [
    "phf",
    "phf_codegen",
    "phf_codegen/test",
    "phf_generator",
    "phf_macros",
    "phf_shared",
    "phf_bench",
    "phf_raw",
]

[profile.release]
debug = true

