[package]
name = "phf_bench"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
edition = "2018"

[dependencies]
phf_generator = { path = "../phf_generator" }
rand = "*"
xz2 = "0.1"
